Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      # Generate a name based on the stage
      UserPoolName: ${self:custom.stage}-${self:service}
      # Set email as an alias
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      # Generate an app client name based on the stage
      ClientName: ${self:custom.stage}-${self:service}-userpool-client
      UserPoolId:
        Ref: CognitoUserPool
      # ExplicitAuthFlows:
      #   - ADMIN_NO_SRP_AUTH            # JRH: not sure why this is here
      # GenerateSecret: false
