import React from 'react';
import logo from './logo.svg';
import './App.css';

import Amplify, { API } from 'aws-amplify';
// file generated by the sls plugin
import awsconfig from './aws-exports';
import { withAuthenticator } from 'aws-amplify-react';

Amplify.configure(awsconfig);

function App() {

  const get = async () => {
    console.log('calling GET');
    const response = await API.get(
      'ApiGatewayRestApi', // function defined in our serverless.yml
      '/test',              // the function's path
      { 'responseType': 'text' }
    );
    console.log(`got ${response}`);
    alert(response);
  };

  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.js</code> and save to reload.
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
        <button onClick={get}>GET</button>
      </header>
    </div>
  );
}

export default withAuthenticator(App, true);